name: Clare Macrae
markdown: kramdown
permalink: /blog/:year/:month/:title
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Setup
title: Clare Macrae
url: https://claremacrae.github.io/

# Recommended by https://help.github.com/en/articles/repository-metadata-on-github-pages
repository: claremacrae/claremacrae.github.io

author:
  name:             Clare Macrae
  email:            

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-redirect-from

#defaults:
#  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
