name: Clare Macrae
markdown: kramdown
permalink: /blog/:year/:month/:title

# Setup
title: Clare Macrae's Blog
url: https://claremacrae.github.io/

# Recommended by https://help.github.com/en/articles/repository-metadata-on-github-pages
repository: claremacrae/claremacrae.github.io

author:
  name:             Clare Macrae
  email:            

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from
