#theme: jekyll-theme-slate
name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Setup
title: Hank Quinlan's Blog
url: http://hankquinlan.github.io

author:
  name:             Hank Quinlan
  email:            hankquinlanhub@gmail.com
