# For options, see https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
name: Clare Macrae
markdown: kramdown
permalink: /blog/:year/:month/:title
paginate: 4 # amount of posts to show
paginate_path: /page:num/

# Setup
title: Clare Macrae
url: https://claremacrae.co.uk/
enforce_ssl: claremacrae.co.uk

# Recommended by https://help.github.com/en/articles/repository-metadata-on-github-pages
repository: claremacrae/claremacrae.github.io

author:
  name:             Clare Macrae
  email:            

remote_theme: "mmistakes/minimal-mistakes@4.15.2"
# See also some customising of colours from this skin in assets/css/main.scss
minimal_mistakes_skin : "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "sidebar"
