#theme: jekyll-theme-slate
name: Clare Macrae
markdown: kramdown
permalink: /blog/:year/:month/:title

# Setup
title: Clare Macrae's Blog
url: https://claremacrae.github.io/

author:
  name:             Clare Macrae
  email:            
