name: Clare Macrae
markdown: kramdown
permalink: /blog/:year/:month/:title
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Setup
title: Clare Macrae
url: https://claremacrae.github.io/

# Recommended by https://help.github.com/en/articles/repository-metadata-on-github-pages
repository: claremacrae/claremacrae.github.io

author:
  name:             Clare Macrae
  email:            

remote_theme: "mmistakes/minimal-mistakes@4.15.2"

plugins:
  - jekyll-redirect-from
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "sidebar"
